<?php $form = $this->form; ?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form) ?>
<!-- Url input text -->
<?php echo $this->formElement($form->get('url')); ?>

<!-- Submit button -->
<?php echo $this->formElement($form->get('submit')); ?>

<!-- Error message -->
<?php echo $this->formElementErrors($form->get('url')); ?>

<!-- CSRF -->
<?php echo $this->formElement($form->get('csrf')); ?>
<?php echo $this->formElementErrors($form->get('csrf')); ?>

<?php echo $this->form()->closeTag() ?>