<?php $form = $this->form; ?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form) ?>
<!-- Comment input text -->
<label><?php echo $this->translate('Add a new subscription') ?></label>
<?php echo $this->formElement($form->get('url')); ?>

<!-- Submit button -->
<?php echo $this->formButton($form->get('subscribe'), 'Add'); ?>

<!-- Error message -->
<?php echo $this->formElementErrors($form->get('url')); ?>

<!-- CSRF -->
<?php echo $this->formElement($form->get('csrf')); ?>
<?php echo $this->formElementErrors($form->get('csrf')); ?>

<?php echo $this->form()->closeTag() ?>