<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <div class="span3 well" id="profile">
                <section>
                    <a href="<?php //echo $this->url('wall', array('username' => $profileData->getUsername())) ?>" title="<?php //printf('%s %s', $profileData->getName(), $profileData->getSurname())  ?>" class="thumbnail">
                        <img src="/images/avatar.png" alt="<?php //printf('%s %s', $profileData->getName(), $profileData->getSurname())  ?>" />
                    </a>
                    <ul>
                        <li>
                            <h3><i class="icon-user"></i> Bio</h3>
                            <p><?php //echo $profileData->getBio() ?></p>
                        </li>
                        <li>
                            <h3><i class="icon-globe"></i> Location</h3>
                            <p><?php //echo $profileData->getLocation() ?></p>
                        </li>
                        <li>
                            <h3><i class="icon-heart"></i> Gender</h3>
                            <p><?php //echo $profileData->getGenderString() ?></p>
                        </li>
                    </ul>
                </section>
            </div>
        </div>
    </div>
</div>