<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">

            <!-- Profile section -->
            <div class="span3 well" id="profile">
                <section>
                    <a href="#" title="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname())  ?>" class="thumbnail">
                        <img src="/images/avatar.png" alt="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname())  ?>" />
                    </a>
                    <ul>
                        <li>
                            <h3><i class="icon-user"></i> Bio</h3>
                            <p><?php echo $profileData->getBio() ?></p>
                        </li>
                        <li>
                            <h3><i class="icon-globe"></i> Location</h3>
                            <p><?php echo $profileData->getLocation() ?></p>
                        </li>
                        <li>
                            <h3><i class="icon-heart"></i> Gender</h3>
                            <p><?php echo $profileData->getGenderString() ?></p>
                        </li>
                    </ul>
                </section>
            </div>

            <!-- Wall profile -->
            <div class="span9" id="wall">
                <section>
                    <!-- Main Stream wall profile -->
                    <div id="wall-stream">
                        <h2><?php printf('%s %s', $profileData->getName(), $profileData->getSurname())  ?></h2>
                        <button class="btn btn-primary" type="button">Edit profile <i class="icon-edit icon-white"></i></button>
                    </div>
                <section>
                <section>
                    <div id="wall-status">
                        <?php echo $this->partial('forms/text-content-form.phtml', array('form' => $textContentForm)); ?>
                    </div>
                </section>
                <section>
                    <ul class="post-list">
                        <?php foreach ($profileData->getStatuses() as $status) : ?>
                            <li class="post">
                                <section>
                                    <a href="#" title="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname())  ?>" class="pull-left thumbnail">
                                        <img src="/images/avatar.png" alt="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname())  ?>" />
                                    </a>
                                    <div class="post-body">
                                        <h4 class="post-heading"><a href="#" title="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname())  ?>"><?php printf('%s %s', $profileData->getName(), $profileData->getSurname())  ?></a></h4>
                                        <p><?php echo $status->getStatus() ?></p>
                                        <ul>
                                            <li><a href="#" title="Comment" class="comment-link"><i class=" icon-comment"></i> Comment</a></li>
                                        </ul>
                                    </div>
                                </section>
                            </li>
                        <?php endforeach; ?>
                    </ul> <!-- Close post list -->
                <section>
            </div> <!-- Close wall profile -->

        </div>
    </div>
</div>
